//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion_Banco.ServiceTransferencias {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Transaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime FechaHoraField;
        
        private int CuentaIdField;
        
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CuentaId {
            get {
                return this.CuentaIdField;
            }
            set {
                if ((this.CuentaIdField.Equals(value) != true)) {
                    this.CuentaIdField = value;
                    this.RaisePropertyChanged("CuentaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NumeroTransaccion {
            get {
                return this.NumeroTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTransaccionField, value) != true)) {
                    this.NumeroTransaccionField = value;
                    this.RaisePropertyChanged("NumeroTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTransferencias.TransferenciasSoap")]
    public interface TransferenciasSoap {
        
        // CODEGEN: Generating message contract since element name numeroCuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposito", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.DepositoResponse Deposito(Integracion_Banco.ServiceTransferencias.DepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposito", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.DepositoResponse> DepositoAsync(Integracion_Banco.ServiceTransferencias.DepositoRequest request);
        
        // CODEGEN: Generating message contract since element name numeroCuentaOrigen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transferir", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.TransferirResponse Transferir(Integracion_Banco.ServiceTransferencias.TransferirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transferir", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TransferirResponse> TransferirAsync(Integracion_Banco.ServiceTransferencias.TransferirRequest request);
        
        // CODEGEN: Generating message contract since element name numeroCuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetirarDinero", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.RetirarDineroResponse RetirarDinero(Integracion_Banco.ServiceTransferencias.RetirarDineroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetirarDinero", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.RetirarDineroResponse> RetirarDineroAsync(Integracion_Banco.ServiceTransferencias.RetirarDineroRequest request);
        
        // CODEGEN: Generating message contract since element name MostrarTransaccionesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTransacciones", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse MostrarTransacciones(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarTransacciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse> MostrarTransaccionesAsync(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest request);
        
        // CODEGEN: Generating message contract since element name Remitente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarTurnoConBilletes", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse InsertarTurnoConBilletes(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarTurnoConBilletes", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse> InsertarTurnoConBilletesAsync(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPrestamo", ReplyAction="*")]
        bool CrearPrestamo(int cliente_id, System.DateTime fecha_inicio, System.DateTime fecha_fin, System.DateTime dia_corte_pago, decimal sueldo_restante, decimal tasa_interes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPrestamo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CrearPrestamoAsync(int cliente_id, System.DateTime fecha_inicio, System.DateTime fecha_fin, System.DateTime dia_corte_pago, decimal sueldo_restante, decimal tasa_interes);
        
        // CODEGEN: Generating message contract since element name Remitente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminarTurno", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse TerminarTurno(Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminarTurno", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse> TerminarTurnoAsync(Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest request);
        
        // CODEGEN: Generating message contract since element name remitente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagoPrestamo", ReplyAction="*")]
        Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse PagoPrestamo(Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagoPrestamo", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse> PagoPrestamoAsync(Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deposito", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.DepositoRequestBody Body;
        
        public DepositoRequest() {
        }
        
        public DepositoRequest(Integracion_Banco.ServiceTransferencias.DepositoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int origen;
        
        public DepositoRequestBody() {
        }
        
        public DepositoRequestBody(string numeroCuenta, decimal cantidad, string descripcion, string remitente, int origen) {
            this.numeroCuenta = numeroCuenta;
            this.cantidad = cantidad;
            this.descripcion = descripcion;
            this.remitente = remitente;
            this.origen = origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.DepositoResponseBody Body;
        
        public DepositoResponse() {
        }
        
        public DepositoResponse(Integracion_Banco.ServiceTransferencias.DepositoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepositoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DepositoResult;
        
        public DepositoResponseBody() {
        }
        
        public DepositoResponseBody(bool DepositoResult) {
            this.DepositoResult = DepositoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transferir", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.TransferirRequestBody Body;
        
        public TransferirRequest() {
        }
        
        public TransferirRequest(Integracion_Banco.ServiceTransferencias.TransferirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroCuentaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroCuentaDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Origen;
        
        public TransferirRequestBody() {
        }
        
        public TransferirRequestBody(string numeroCuentaOrigen, string numeroCuentaDestino, decimal monto, string Remitente, int Origen) {
            this.numeroCuentaOrigen = numeroCuentaOrigen;
            this.numeroCuentaDestino = numeroCuentaDestino;
            this.monto = monto;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransferirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransferirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.TransferirResponseBody Body;
        
        public TransferirResponse() {
        }
        
        public TransferirResponse(Integracion_Banco.ServiceTransferencias.TransferirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransferirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TransferirResult;
        
        public TransferirResponseBody() {
        }
        
        public TransferirResponseBody(bool TransferirResult) {
            this.TransferirResult = TransferirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarDineroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetirarDinero", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.RetirarDineroRequestBody Body;
        
        public RetirarDineroRequest() {
        }
        
        public RetirarDineroRequest(Integracion_Banco.ServiceTransferencias.RetirarDineroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetirarDineroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public RetirarDineroRequestBody() {
        }
        
        public RetirarDineroRequestBody(string numeroCuenta, decimal monto) {
            this.numeroCuenta = numeroCuenta;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarDineroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetirarDineroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.RetirarDineroResponseBody Body;
        
        public RetirarDineroResponse() {
        }
        
        public RetirarDineroResponse(Integracion_Banco.ServiceTransferencias.RetirarDineroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetirarDineroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RetirarDineroResult;
        
        public RetirarDineroResponseBody() {
        }
        
        public RetirarDineroResponseBody(bool RetirarDineroResult) {
            this.RetirarDineroResult = RetirarDineroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTransaccionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTransacciones", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequestBody Body;
        
        public MostrarTransaccionesRequest() {
        }
        
        public MostrarTransaccionesRequest(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarTransaccionesRequestBody {
        
        public MostrarTransaccionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarTransaccionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarTransaccionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponseBody Body;
        
        public MostrarTransaccionesResponse() {
        }
        
        public MostrarTransaccionesResponse(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarTransaccionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion_Banco.ServiceTransferencias.Transaccion[] MostrarTransaccionesResult;
        
        public MostrarTransaccionesResponseBody() {
        }
        
        public MostrarTransaccionesResponseBody(Integracion_Banco.ServiceTransferencias.Transaccion[] MostrarTransaccionesResult) {
            this.MostrarTransaccionesResult = MostrarTransaccionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarTurnoConBilletesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarTurnoConBilletes", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequestBody Body;
        
        public InsertarTurnoConBilletesRequest() {
        }
        
        public InsertarTurnoConBilletesRequest(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarTurnoConBilletesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int empleado_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime hora_inicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int denominacion1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int denominacion5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int denominacion10;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int denominacion25;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int denominacion50;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int denominacion100;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int denominacion200;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int denominacion500;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int denominacion1000;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int denominacion2000;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int Origen;
        
        public InsertarTurnoConBilletesRequestBody() {
        }
        
        public InsertarTurnoConBilletesRequestBody(int empleado_id, System.DateTime fecha, System.DateTime hora_inicio, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            this.empleado_id = empleado_id;
            this.fecha = fecha;
            this.hora_inicio = hora_inicio;
            this.denominacion1 = denominacion1;
            this.denominacion5 = denominacion5;
            this.denominacion10 = denominacion10;
            this.denominacion25 = denominacion25;
            this.denominacion50 = denominacion50;
            this.denominacion100 = denominacion100;
            this.denominacion200 = denominacion200;
            this.denominacion500 = denominacion500;
            this.denominacion1000 = denominacion1000;
            this.denominacion2000 = denominacion2000;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarTurnoConBilletesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarTurnoConBilletesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponseBody Body;
        
        public InsertarTurnoConBilletesResponse() {
        }
        
        public InsertarTurnoConBilletesResponse(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarTurnoConBilletesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertarTurnoConBilletesResult;
        
        public InsertarTurnoConBilletesResponseBody() {
        }
        
        public InsertarTurnoConBilletesResponseBody(int InsertarTurnoConBilletesResult) {
            this.InsertarTurnoConBilletesResult = InsertarTurnoConBilletesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminarTurnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminarTurno", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.TerminarTurnoRequestBody Body;
        
        public TerminarTurnoRequest() {
        }
        
        public TerminarTurnoRequest(Integracion_Banco.ServiceTransferencias.TerminarTurnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TerminarTurnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int turno_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime hora_fin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int denominacion1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int denominacion5;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int denominacion10;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int denominacion25;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int denominacion50;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int denominacion100;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int denominacion200;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int denominacion500;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int denominacion1000;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int denominacion2000;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int Origen;
        
        public TerminarTurnoRequestBody() {
        }
        
        public TerminarTurnoRequestBody(int turno_id, System.DateTime hora_fin, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            this.turno_id = turno_id;
            this.hora_fin = hora_fin;
            this.denominacion1 = denominacion1;
            this.denominacion5 = denominacion5;
            this.denominacion10 = denominacion10;
            this.denominacion25 = denominacion25;
            this.denominacion50 = denominacion50;
            this.denominacion100 = denominacion100;
            this.denominacion200 = denominacion200;
            this.denominacion500 = denominacion500;
            this.denominacion1000 = denominacion1000;
            this.denominacion2000 = denominacion2000;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminarTurnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminarTurnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.TerminarTurnoResponseBody Body;
        
        public TerminarTurnoResponse() {
        }
        
        public TerminarTurnoResponse(Integracion_Banco.ServiceTransferencias.TerminarTurnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TerminarTurnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TerminarTurnoResult;
        
        public TerminarTurnoResponseBody() {
        }
        
        public TerminarTurnoResponseBody(bool TerminarTurnoResult) {
            this.TerminarTurnoResult = TerminarTurnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoPrestamo", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.PagoPrestamoRequestBody Body;
        
        public PagoPrestamoRequest() {
        }
        
        public PagoPrestamoRequest(Integracion_Banco.ServiceTransferencias.PagoPrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagoPrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int prestamo_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto_pago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int origen;
        
        public PagoPrestamoRequestBody() {
        }
        
        public PagoPrestamoRequestBody(int prestamo_id, decimal monto_pago, string remitente, int origen) {
            this.prestamo_id = prestamo_id;
            this.monto_pago = monto_pago;
            this.remitente = remitente;
            this.origen = origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoPrestamoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Integracion_Banco.ServiceTransferencias.PagoPrestamoResponseBody Body;
        
        public PagoPrestamoResponse() {
        }
        
        public PagoPrestamoResponse(Integracion_Banco.ServiceTransferencias.PagoPrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagoPrestamoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PagoPrestamoResult;
        
        public PagoPrestamoResponseBody() {
        }
        
        public PagoPrestamoResponseBody(bool PagoPrestamoResult) {
            this.PagoPrestamoResult = PagoPrestamoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransferenciasSoapChannel : Integracion_Banco.ServiceTransferencias.TransferenciasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferenciasSoapClient : System.ServiceModel.ClientBase<Integracion_Banco.ServiceTransferencias.TransferenciasSoap>, Integracion_Banco.ServiceTransferencias.TransferenciasSoap {
        
        public TransferenciasSoapClient() {
        }
        
        public TransferenciasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferenciasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferenciasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferenciasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.DepositoResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.Deposito(Integracion_Banco.ServiceTransferencias.DepositoRequest request) {
            return base.Channel.Deposito(request);
        }
        
        public bool Deposito(string numeroCuenta, decimal cantidad, string descripcion, string remitente, int origen) {
            Integracion_Banco.ServiceTransferencias.DepositoRequest inValue = new Integracion_Banco.ServiceTransferencias.DepositoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.DepositoRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.cantidad = cantidad;
            inValue.Body.descripcion = descripcion;
            inValue.Body.remitente = remitente;
            inValue.Body.origen = origen;
            Integracion_Banco.ServiceTransferencias.DepositoResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).Deposito(inValue);
            return retVal.Body.DepositoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.DepositoResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.DepositoAsync(Integracion_Banco.ServiceTransferencias.DepositoRequest request) {
            return base.Channel.DepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.DepositoResponse> DepositoAsync(string numeroCuenta, decimal cantidad, string descripcion, string remitente, int origen) {
            Integracion_Banco.ServiceTransferencias.DepositoRequest inValue = new Integracion_Banco.ServiceTransferencias.DepositoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.DepositoRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.cantidad = cantidad;
            inValue.Body.descripcion = descripcion;
            inValue.Body.remitente = remitente;
            inValue.Body.origen = origen;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).DepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.TransferirResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.Transferir(Integracion_Banco.ServiceTransferencias.TransferirRequest request) {
            return base.Channel.Transferir(request);
        }
        
        public bool Transferir(string numeroCuentaOrigen, string numeroCuentaDestino, decimal monto, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.TransferirRequest inValue = new Integracion_Banco.ServiceTransferencias.TransferirRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.TransferirRequestBody();
            inValue.Body.numeroCuentaOrigen = numeroCuentaOrigen;
            inValue.Body.numeroCuentaDestino = numeroCuentaDestino;
            inValue.Body.monto = monto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Integracion_Banco.ServiceTransferencias.TransferirResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).Transferir(inValue);
            return retVal.Body.TransferirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TransferirResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.TransferirAsync(Integracion_Banco.ServiceTransferencias.TransferirRequest request) {
            return base.Channel.TransferirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TransferirResponse> TransferirAsync(string numeroCuentaOrigen, string numeroCuentaDestino, decimal monto, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.TransferirRequest inValue = new Integracion_Banco.ServiceTransferencias.TransferirRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.TransferirRequestBody();
            inValue.Body.numeroCuentaOrigen = numeroCuentaOrigen;
            inValue.Body.numeroCuentaDestino = numeroCuentaDestino;
            inValue.Body.monto = monto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).TransferirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.RetirarDineroResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.RetirarDinero(Integracion_Banco.ServiceTransferencias.RetirarDineroRequest request) {
            return base.Channel.RetirarDinero(request);
        }
        
        public bool RetirarDinero(string numeroCuenta, decimal monto) {
            Integracion_Banco.ServiceTransferencias.RetirarDineroRequest inValue = new Integracion_Banco.ServiceTransferencias.RetirarDineroRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.RetirarDineroRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.monto = monto;
            Integracion_Banco.ServiceTransferencias.RetirarDineroResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).RetirarDinero(inValue);
            return retVal.Body.RetirarDineroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.RetirarDineroResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.RetirarDineroAsync(Integracion_Banco.ServiceTransferencias.RetirarDineroRequest request) {
            return base.Channel.RetirarDineroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.RetirarDineroResponse> RetirarDineroAsync(string numeroCuenta, decimal monto) {
            Integracion_Banco.ServiceTransferencias.RetirarDineroRequest inValue = new Integracion_Banco.ServiceTransferencias.RetirarDineroRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.RetirarDineroRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.monto = monto;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).RetirarDineroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.MostrarTransacciones(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest request) {
            return base.Channel.MostrarTransacciones(request);
        }
        
        public Integracion_Banco.ServiceTransferencias.Transaccion[] MostrarTransacciones() {
            Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest inValue = new Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequestBody();
            Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).MostrarTransacciones(inValue);
            return retVal.Body.MostrarTransaccionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.MostrarTransaccionesAsync(Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest request) {
            return base.Channel.MostrarTransaccionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.MostrarTransaccionesResponse> MostrarTransaccionesAsync() {
            Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest inValue = new Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.MostrarTransaccionesRequestBody();
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).MostrarTransaccionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.InsertarTurnoConBilletes(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest request) {
            return base.Channel.InsertarTurnoConBilletes(request);
        }
        
        public int InsertarTurnoConBilletes(int empleado_id, System.DateTime fecha, System.DateTime hora_inicio, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest inValue = new Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequestBody();
            inValue.Body.empleado_id = empleado_id;
            inValue.Body.fecha = fecha;
            inValue.Body.hora_inicio = hora_inicio;
            inValue.Body.denominacion1 = denominacion1;
            inValue.Body.denominacion5 = denominacion5;
            inValue.Body.denominacion10 = denominacion10;
            inValue.Body.denominacion25 = denominacion25;
            inValue.Body.denominacion50 = denominacion50;
            inValue.Body.denominacion100 = denominacion100;
            inValue.Body.denominacion200 = denominacion200;
            inValue.Body.denominacion500 = denominacion500;
            inValue.Body.denominacion1000 = denominacion1000;
            inValue.Body.denominacion2000 = denominacion2000;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).InsertarTurnoConBilletes(inValue);
            return retVal.Body.InsertarTurnoConBilletesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.InsertarTurnoConBilletesAsync(Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest request) {
            return base.Channel.InsertarTurnoConBilletesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesResponse> InsertarTurnoConBilletesAsync(int empleado_id, System.DateTime fecha, System.DateTime hora_inicio, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest inValue = new Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.InsertarTurnoConBilletesRequestBody();
            inValue.Body.empleado_id = empleado_id;
            inValue.Body.fecha = fecha;
            inValue.Body.hora_inicio = hora_inicio;
            inValue.Body.denominacion1 = denominacion1;
            inValue.Body.denominacion5 = denominacion5;
            inValue.Body.denominacion10 = denominacion10;
            inValue.Body.denominacion25 = denominacion25;
            inValue.Body.denominacion50 = denominacion50;
            inValue.Body.denominacion100 = denominacion100;
            inValue.Body.denominacion200 = denominacion200;
            inValue.Body.denominacion500 = denominacion500;
            inValue.Body.denominacion1000 = denominacion1000;
            inValue.Body.denominacion2000 = denominacion2000;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).InsertarTurnoConBilletesAsync(inValue);
        }
        
        public bool CrearPrestamo(int cliente_id, System.DateTime fecha_inicio, System.DateTime fecha_fin, System.DateTime dia_corte_pago, decimal sueldo_restante, decimal tasa_interes) {
            return base.Channel.CrearPrestamo(cliente_id, fecha_inicio, fecha_fin, dia_corte_pago, sueldo_restante, tasa_interes);
        }
        
        public System.Threading.Tasks.Task<bool> CrearPrestamoAsync(int cliente_id, System.DateTime fecha_inicio, System.DateTime fecha_fin, System.DateTime dia_corte_pago, decimal sueldo_restante, decimal tasa_interes) {
            return base.Channel.CrearPrestamoAsync(cliente_id, fecha_inicio, fecha_fin, dia_corte_pago, sueldo_restante, tasa_interes);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.TerminarTurno(Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest request) {
            return base.Channel.TerminarTurno(request);
        }
        
        public bool TerminarTurno(int turno_id, System.DateTime hora_fin, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest inValue = new Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.TerminarTurnoRequestBody();
            inValue.Body.turno_id = turno_id;
            inValue.Body.hora_fin = hora_fin;
            inValue.Body.denominacion1 = denominacion1;
            inValue.Body.denominacion5 = denominacion5;
            inValue.Body.denominacion10 = denominacion10;
            inValue.Body.denominacion25 = denominacion25;
            inValue.Body.denominacion50 = denominacion50;
            inValue.Body.denominacion100 = denominacion100;
            inValue.Body.denominacion200 = denominacion200;
            inValue.Body.denominacion500 = denominacion500;
            inValue.Body.denominacion1000 = denominacion1000;
            inValue.Body.denominacion2000 = denominacion2000;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).TerminarTurno(inValue);
            return retVal.Body.TerminarTurnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.TerminarTurnoAsync(Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest request) {
            return base.Channel.TerminarTurnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.TerminarTurnoResponse> TerminarTurnoAsync(int turno_id, System.DateTime hora_fin, int denominacion1, int denominacion5, int denominacion10, int denominacion25, int denominacion50, int denominacion100, int denominacion200, int denominacion500, int denominacion1000, int denominacion2000, string Remitente, int Origen) {
            Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest inValue = new Integracion_Banco.ServiceTransferencias.TerminarTurnoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.TerminarTurnoRequestBody();
            inValue.Body.turno_id = turno_id;
            inValue.Body.hora_fin = hora_fin;
            inValue.Body.denominacion1 = denominacion1;
            inValue.Body.denominacion5 = denominacion5;
            inValue.Body.denominacion10 = denominacion10;
            inValue.Body.denominacion25 = denominacion25;
            inValue.Body.denominacion50 = denominacion50;
            inValue.Body.denominacion100 = denominacion100;
            inValue.Body.denominacion200 = denominacion200;
            inValue.Body.denominacion500 = denominacion500;
            inValue.Body.denominacion1000 = denominacion1000;
            inValue.Body.denominacion2000 = denominacion2000;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).TerminarTurnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse Integracion_Banco.ServiceTransferencias.TransferenciasSoap.PagoPrestamo(Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest request) {
            return base.Channel.PagoPrestamo(request);
        }
        
        public bool PagoPrestamo(int prestamo_id, decimal monto_pago, string remitente, int origen) {
            Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest inValue = new Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.PagoPrestamoRequestBody();
            inValue.Body.prestamo_id = prestamo_id;
            inValue.Body.monto_pago = monto_pago;
            inValue.Body.remitente = remitente;
            inValue.Body.origen = origen;
            Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse retVal = ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).PagoPrestamo(inValue);
            return retVal.Body.PagoPrestamoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse> Integracion_Banco.ServiceTransferencias.TransferenciasSoap.PagoPrestamoAsync(Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest request) {
            return base.Channel.PagoPrestamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion_Banco.ServiceTransferencias.PagoPrestamoResponse> PagoPrestamoAsync(int prestamo_id, decimal monto_pago, string remitente, int origen) {
            Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest inValue = new Integracion_Banco.ServiceTransferencias.PagoPrestamoRequest();
            inValue.Body = new Integracion_Banco.ServiceTransferencias.PagoPrestamoRequestBody();
            inValue.Body.prestamo_id = prestamo_id;
            inValue.Body.monto_pago = monto_pago;
            inValue.Body.remitente = remitente;
            inValue.Body.origen = origen;
            return ((Integracion_Banco.ServiceTransferencias.TransferenciasSoap)(this)).PagoPrestamoAsync(inValue);
        }
    }
}
